package waf

import (
	"strings"

	"github.com/guaidao2/crackweb/internal/httpmsg"
)

// Signature describes what a refusal looks like from a particular target.
type Signature struct {
	// Statuses are the status codes this target uses to refuse.
	Statuses []int
	// BodyMarkers are substrings that appear in a refusal page.
	BodyMarkers []string
	// HeaderMarkers are response headers that appear only on a refusal.
	HeaderMarkers []string
}

// defaultSignature is the fallback when nothing more specific is known.
func defaultSignature() Signature {
	return Signature{
		Statuses: []int{403, 406, 501, 999},
		BodyMarkers: []string{
			"access denied", "request rejected", "not acceptable",
			"blocked", "forbidden", "security policy",
			"请求被拦截", "访问被拒绝", "非法请求",
		},
	}
}

// matches reports whether a response satisfies this signature.
//
// The status code alone is not enough: applications return 403 for their own
// authorisation failures, and escalating payloads because a page said "no" to
// a different question would burn requests without gaining anything. A status
// code must therefore be accompanied by something that reads like a refusal.
func (s Signature) matches(resp *httpmsg.Response) bool {
	if resp == nil {
		return false
	}
	if !containsInt(s.Statuses, resp.Status) {
		return false
	}
	for _, marker := range s.BodyMarkers {
		if containsFold(string(resp.Body), marker) {
			return true
		}
	}
	for _, name := range s.HeaderMarkers {
		if resp.Header.Has(name) {
			return true
		}
	}
	// A block status with a tiny body is a bare refusal even without wording:
	// real applications send an HTML error page, WAFs send a stub.
	if len(resp.Body) < 512 && resp.Status != 403 {
		return true
	}
	return false
}

// genericBlock is the conservative test used when no WAF was identified.
func genericBlock(resp *httpmsg.Response) bool {
	if resp == nil || !containsInt([]int{403, 406, 501, 999}, resp.Status) {
		return false
	}
	body := strings.ToLower(string(resp.Body))
	for _, marker := range []string{
		"access denied", "request rejected", "not acceptable", "blocked",
		"security policy", "incident id", "ray id",
		"请求被拦截", "访问被拒绝",
	} {
		if strings.Contains(body, marker) {
			return true
		}
	}
	// A refusal stub with no wording at all, from a status code only a WAF
	// uses. 403 is excluded because applications use it for their own denials.
	if resp.Status == 406 || resp.Status == 501 || resp.Status == 999 {
		return len(resp.Body) < 1024
	}
	return false
}

// vendorPattern recognises one WAF from a response.
type vendorPattern struct {
	// Name is the vendor label shown to the user.
	Name string
	// Headers are response headers whose presence identifies the vendor.
	Headers []string
	// HeaderValues maps a header to a substring its value must contain.
	HeaderValues map[string]string
	// BodyMarkers are substrings of a refusal page that identify the vendor.
	BodyMarkers []string
	// ServerContains matches against the Server header.
	ServerContains string
}

// vendors is the fingerprint table. Order matters only for readability: a
// response is checked against every entry and the first match wins, so the list
// is ordered from most specific to least.
var vendors = []vendorPattern{
	{
		Name:           "Cloudflare",
		Headers:        []string{"cf-ray", "cf-mitigated", "cf-cache-status"},
		BodyMarkers:    []string{"Attention Required! | Cloudflare", "Ray ID", "Cloudflare Ray ID"},
		ServerContains: "cloudflare",
	},
	{
		Name:        "AWS WAF",
		Headers:     []string{"x-amzn-requestid", "x-amz-cf-id", "x-amzn-errortype"},
		BodyMarkers: []string{"Request blocked", "aws-waf"},
	},
	{
		Name:        "Akamai",
		Headers:     []string{"x-akamai-transformed", "akamai-grn", "x-akamai-request-id"},
		BodyMarkers: []string{"Access Denied", "Reference #"},
	},
	{
		Name:        "Imperva Incapsula",
		Headers:     []string{"x-iinfo", "x-cdn"},
		BodyMarkers: []string{"Incapsula incident ID", "_Incapsula_Resource"},
	},
	{
		Name:        "F5 BIG-IP ASM",
		Headers:     []string{"x-wa-info", "x-cnection"},
		BodyMarkers: []string{"The requested URL was rejected", "support ID"},
	},
	{
		Name:        "ModSecurity",
		Headers:     []string{"mod_security", "x-mod-security"},
		BodyMarkers: []string{"ModSecurity", "mod_security", "This error was generated by Mod_Security"},
	},
	{
		Name:        "Sucuri",
		Headers:     []string{"x-sucuri-id", "x-sucuri-cache"},
		BodyMarkers: []string{"Sucuri WebSite Firewall", "sucuri.net"},
	},
	{
		Name:        "Wallarm",
		Headers:     []string{"x-wallarm-*"},
		BodyMarkers: []string{"Wallarm", "blocked-by-wallarm"},
	},
	{
		Name:        "Fortinet FortiWeb",
		BodyMarkers: []string{"FortiWeb", ".fgd_icon"},
	},
	{
		Name:        "Barracuda",
		BodyMarkers: []string{"Barracuda", "barra_counter_session"},
	},
	{
		Name:           "安全狗 SafeDog",
		BodyMarkers:    []string{"安全狗", "Safedog", "safedog", "waf.safedog"},
		ServerContains: "safedog",
	},
	{
		Name:        "宝塔 WAF",
		BodyMarkers: []string{"宝塔", "BT-Panel", "/btwaf/", "btwaf"},
	},
	{
		Name:           "长亭雷池 SafeLine",
		BodyMarkers:    []string{"SafeLine", "雷池", "safeline"},
		ServerContains: "safeline",
	},
	{
		Name:        "阿里云 WAF",
		Headers:     []string{"x-waf-*"},
		BodyMarkers: []string{"aliyun", "阿里云", "errors.aliyun.com"},
	},
	{
		Name:        "腾讯云 WAF",
		BodyMarkers: []string{"waf.tencent", "Tencent Cloud", "腾讯云"},
	},
	{
		Name:        "360 WAF",
		BodyMarkers: []string{"360wzws", "wzws", "360网站卫士"},
	},
	{
		Name:        "长亭 Chaitin",
		BodyMarkers: []string{"Chaitin", "长亭科技"},
	},
	{
		Name:        "Google Cloud Armor",
		BodyMarkers: []string{"google cloud armor", "gcloud"},
	},
	{
		Name:        "Citrix NetScaler",
		Headers:     []string{"x-citrix-transactionid", "ns_af", "citrix_ns_id"},
		BodyMarkers: []string{"NetScaler", "Citrix"},
	},
	{
		Name:        "HAProxy",
		Headers:     []string{"x-haproxy-*"},
		BodyMarkers: []string{"HAProxy"},
	},
}

// Identify names the WAF behind a response, or "" when nothing is recognised.
func Identify(resp *httpmsg.Response) string {
	if resp == nil {
		return ""
	}
	for _, vendor := range vendors {
		if vendor.identifies(resp) {
			return vendor.Name
		}
	}
	return ""
}

// identifies reports whether a response carries this vendor's fingerprint.
func (v vendorPattern) identifies(resp *httpmsg.Response) bool {
	for _, name := range v.Headers {
		if strings.HasSuffix(name, "*") {
			prefix := strings.TrimSuffix(name, "*")
			for _, field := range resp.Header.All() {
				if strings.HasPrefix(strings.ToLower(field.Name), prefix) {
					return true
				}
			}
			continue
		}
		if resp.Header.Has(name) {
			return true
		}
	}
	for name, want := range v.HeaderValues {
		if containsFold(resp.Header.Get(name), want) {
			return true
		}
	}
	if v.ServerContains != "" && containsFold(resp.Header.Get("Server"), v.ServerContains) {
		return true
	}
	if len(resp.Body) > 0 && len(resp.Body) < 1<<20 {
		body := string(resp.Body)
		for _, marker := range v.BodyMarkers {
			if containsFold(body, marker) {
				return true
			}
		}
	}
	return false
}

// Classify decides whether a probe response indicates a WAF, comparing it
// against the response to a harmless request.
//
// The rule is deliberately strict. A block status code that the baseline did
// not produce is the primary signal; vendor fingerprints and refusal wording
// confirm it. Anything weaker — "the two responses differ" — is not used,
// because applications answer differently for their own reasons and a wrong
// verdict costs four generations of wasted mutation on every later payload.
func Classify(baseline, probe *httpmsg.Response) (blocked bool, vendor string, signature Signature) {
	if probe == nil {
		return false, "", Signature{}
	}

	vendor = Identify(probe)

	// A vendor fingerprint on the refusal is conclusive on its own.
	if vendor != "" && probe.Status >= 400 {
		return true, vendor, Signature{
			Statuses:    []int{probe.Status},
			BodyMarkers: refusalMarkers(probe),
		}
	}

	baselineStatus := 0
	if baseline != nil {
		baselineStatus = baseline.Status
	}
	if probe.Status == baselineStatus || !containsInt([]int{403, 406, 419, 501, 999}, probe.Status) {
		return false, vendor, Signature{}
	}

	// The status changed to a block code. Confirm it reads like a refusal
	// rather than an application-level authorisation failure.
	markers := refusalMarkers(probe)
	if len(markers) > 0 {
		return true, vendor, Signature{Statuses: []int{probe.Status}, BodyMarkers: markers}
	}
	return false, vendor, Signature{}
}

// refusalMarkers returns the refusal wording present in a response, which
// becomes the signature later responses are matched against.
func refusalMarkers(resp *httpmsg.Response) []string {
	if resp == nil || len(resp.Body) == 0 {
		return nil
	}
	body := string(resp.Body)
	var found []string
	for _, marker := range []string{
		"Access Denied", "Request Rejected", "Not Acceptable", "Request blocked",
		"blocked", "forbidden", "security policy", "incident",
		"请求被拦截", "访问被拒绝", "非法请求", "拦截",
	} {
		if containsFold(body, marker) {
			found = append(found, marker)
		}
	}
	return found
}

// containsInt reports whether a slice holds an int.
func containsInt(values []int, want int) bool {
	for _, v := range values {
		if v == want {
			return true
		}
	}
	return false
}

// containsFold reports whether haystack contains needle, case-insensitively.
func containsFold(haystack, needle string) bool {
	if needle == "" {
		return false
	}
	if len(haystack) < len(needle) {
		return false
	}
	// ASCII-lowercase both sides. Vendor markers that contain non-ASCII (the
	// Chinese ones) are compared byte-for-byte, which is correct because their
	// UTF-8 bytes are already lower-case in the sense that matters.
	lowerHaystack := strings.ToLower(haystack)
	lowerNeedle := strings.ToLower(needle)
	return strings.Contains(lowerHaystack, lowerNeedle)
}
