package waf

import (
	"net/http"
	"testing"

	"github.com/guaidao2/crackweb/internal/httpmsg"
)

// resp builds a response for tests.
func resp(status int, body string, headers ...string) *httpmsg.Response {
	h := httpmsg.Header{}
	for i := 0; i+1 < len(headers); i += 2 {
		h.Add(headers[i], headers[i+1])
	}
	if !h.Has("Content-Type") {
		h.Add("Content-Type", "text/html")
	}
	return &httpmsg.Response{Status: status, Header: h, Body: []byte(body)}
}

func TestIdentifyKnownVendors(t *testing.T) {
	cases := []struct {
		name string
		resp *httpmsg.Response
		want string
	}{
		{
			name: "cloudflare by header",
			resp: resp(403, "blocked", "cf-ray", "7d3f2a1b8c9d-LAX"),
			want: "Cloudflare",
		},
		{
			name: "cloudflare by server",
			resp: resp(403, "nope", "Server", "cloudflare"),
			want: "Cloudflare",
		},
		{
			name: "cloudflare by body",
			resp: resp(403, "<title>Attention Required! | Cloudflare</title>"),
			want: "Cloudflare",
		},
		{
			name: "modsecurity",
			resp: resp(406, "Not Acceptable! This error was generated by Mod_Security"),
			want: "ModSecurity",
		},
		{
			name: "safedog (Chinese vendor, body marker)",
			resp: resp(403, "<html><body>安全狗 拦截</body></html>"),
			want: "安全狗 SafeDog",
		},
		{
			name: "safeline",
			resp: resp(403, "<html>SafeLine 雷池 WAF</html>"),
			want: "长亭雷池 SafeLine",
		},
		{
			name: "imperva",
			resp: resp(403, "Incapsula incident ID: 1234567890"),
			want: "Imperva Incapsula",
		},
		{
			name: "f5",
			resp: resp(403, "The requested URL was rejected. support ID"),
			want: "F5 BIG-IP ASM",
		},
		{
			name: "aws by header",
			resp: resp(403, "Request blocked", "x-amzn-requestid", "abc-123"),
			want: "AWS WAF",
		},
		{
			name: "ordinary application",
			resp: resp(404, "<html><body>Page not found</body></html>"),
			want: "",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := Identify(tc.resp); got != tc.want {
				t.Errorf("Identify() = %q, want %q", got, tc.want)
			}
		})
	}
}

func TestClassifyDetectsBlock(t *testing.T) {
	baseline := resp(200, "<html><body>search results</body></html>")
	probe := resp(403, "<html><body>Access Denied - this request was blocked</body></html>")

	blocked, vendor, signature := Classify(baseline, probe)
	if !blocked {
		t.Fatal("a block status with refusal wording was not recognised")
	}
	if len(signature.Statuses) == 0 || signature.Statuses[0] != 403 {
		t.Errorf("signature does not carry the status: %+v", signature)
	}
	if len(signature.BodyMarkers) == 0 {
		t.Error("signature carries no wording to match later responses against")
	}
	_ = vendor
}

// TestClassifyIgnoresApplicationDenials is the conservative half of detection:
// an application's own 403 must not be mistaken for a WAF, or every payload
// would be escalated for nothing.
func TestClassifyIgnoresApplicationDenials(t *testing.T) {
	cases := map[string]*httpmsg.Response{
		"application authorisation failure": resp(403, "<html><body>You do not have permission to view this order.</body></html>"),
		"origin crash":                      resp(500, "<html><body>Internal Server Error</body></html>"),
		"unchanged status":                  resp(200, "<html><body>fine</body></html>"),
		"redirect to login":                 resp(302, ""),
	}

	baseline := resp(200, "<html><body>search results</body></html>")
	for name, probe := range cases {
		t.Run(name, func(t *testing.T) {
			if blocked, _, _ := Classify(baseline, probe); blocked {
				t.Error("classified as a WAF block")
			}
		})
	}
}

func TestClassifyDetectsVendorBlockWithoutWording(t *testing.T) {
	// A bare 403 carrying a vendor header is conclusive even with no prose.
	baseline := resp(200, "ok")
	probe := resp(403, "", "cf-ray", "abc-LAX")

	blocked, vendor, _ := Classify(baseline, probe)
	if !blocked {
		t.Fatal("a vendor-fingerprinted refusal was not recognised")
	}
	if vendor != "Cloudflare" {
		t.Errorf("vendor = %q, want Cloudflare", vendor)
	}
}

func TestStateLifecycle(t *testing.T) {
	state := NewState(true)

	if !state.NeedsProbe("example.com") {
		t.Error("a fresh target should need a probe")
	}
	if state.Protected("example.com") {
		t.Error("a fresh target should not be marked protected")
	}

	state.MarkProbed("example.com", "Cloudflare", Signature{Statuses: []int{403}})
	if state.NeedsProbe("example.com") {
		t.Error("the target still needs a probe after being probed")
	}
	if !state.Protected("example.com") {
		t.Error("the target is not marked protected after identifying a WAF")
	}
	if got := state.Vendor("example.com"); got != "Cloudflare" {
		t.Errorf("Vendor() = %q", got)
	}
}

func TestStateFloorOnlyRises(t *testing.T) {
	state := NewState(true)

	if got := state.Floor("example.com", "sqli-error"); got != 0 {
		t.Errorf("initial floor = %d, want 0", got)
	}
	state.Raise("example.com", "sqli-error", 2)
	if got := state.Floor("example.com", "sqli-error"); got != 2 {
		t.Errorf("floor = %d, want 2", got)
	}
	// A later, lower observation must not undo what was learned.
	state.Raise("example.com", "sqli-error", 1)
	if got := state.Floor("example.com", "sqli-error"); got != 2 {
		t.Errorf("floor = %d, want it to stay at 2", got)
	}
	// Floors are per check.
	if got := state.Floor("example.com", "xss-reflected"); got != 0 {
		t.Errorf("another check's floor = %d, want 0", got)
	}
	// And per host.
	if got := state.Floor("other.example", "sqli-error"); got != 0 {
		t.Errorf("another host's floor = %d, want 0", got)
	}
}

func TestStateDisabled(t *testing.T) {
	state := NewState(false)
	if state.Enabled() {
		t.Error("Enabled() = true for a disabled state")
	}
	if state.NeedsProbe("example.com") {
		t.Error("a disabled state still wants to probe")
	}
	// A nil state must be safe: callers hold it optionally.
	var nilState *State
	if nilState.Enabled() || nilState.Protected("x") || nilState.Floor("x", "y") != 0 {
		t.Error("a nil state is not safe to use")
	}
	nilState.Raise("x", "y", 2)
	nilState.MarkProbed("x", "", Signature{})
}

func TestIsBlockedUsesTheLearnedSignature(t *testing.T) {
	state := NewState(true)
	state.MarkProbed("example.com", "Test WAF", Signature{
		Statuses:    []int{418},
		BodyMarkers: []string{"teapot policy violation"},
	})

	blocked := resp(418, "<html>teapot policy violation</html>")
	if !state.IsBlocked("example.com", blocked) {
		t.Error("a response matching the learned signature was not treated as blocked")
	}

	// A status the signature does not list is not a block.
	other := resp(403, "<html>teapot policy violation</html>")
	if state.IsBlocked("example.com", other) {
		t.Error("a status outside the learned signature was treated as blocked")
	}
}

// TestIsBlockedIsConservativeWithoutDetection guards the case that matters
// most for cost: no WAF was found, so only unmistakable refusals count.
func TestIsBlockedIsConservativeWithoutDetection(t *testing.T) {
	state := NewState(true)

	obvious := resp(406, "Not Acceptable")
	if !state.IsBlocked("unprobed.example", obvious) {
		t.Error("an unmistakable refusal was not recognised without prior detection")
	}

	applicationDenial := resp(403, "<html><body>You may not edit this record.</body></html>")
	if state.IsBlocked("unprobed.example", applicationDenial) {
		t.Error("an application-level 403 was treated as a WAF block")
	}

	crash := resp(503, "<html>Service Unavailable</html>")
	if state.IsBlocked("unprobed.example", crash) {
		t.Error("an origin failure was treated as a WAF block")
	}
}

func TestSignatureRequiresWordingForOrdinaryCodes(t *testing.T) {
	// 403 is used by applications for their own denials, so it needs wording.
	sig := defaultSignature()

	withWording := resp(403, "<html>Access Denied by security policy</html>")
	if !sig.matches(withWording) {
		t.Error("403 with refusal wording did not match")
	}

	bareApplication403 := resp(403, "<html><body>Admin only.</body></html>")
	if sig.matches(bareApplication403) {
		t.Error("a bare 403 matched the default signature")
	}

	// 406 is not something an application sends by accident.
	bareNotAcceptable := resp(406, "nope")
	if !sig.matches(bareNotAcceptable) {
		t.Error("a 406 did not match")
	}
}

func TestSummariesAreSortedAndCopied(t *testing.T) {
	state := NewState(true)
	state.MarkProbed("zebra.example", "Cloudflare", Signature{Statuses: []int{403}})
	state.MarkProbed("alpha.example", "", Signature{})
	state.Raise("alpha.example", "sqli-error", 3)

	summaries := state.Summaries()
	if len(summaries) != 2 {
		t.Fatalf("got %d summaries, want 2", len(summaries))
	}
	if summaries[0].Host != "alpha.example" {
		t.Errorf("summaries are not sorted: %+v", summaries)
	}
	if summaries[0].Floors["sqli-error"] != 3 {
		t.Errorf("floor was not reported: %+v", summaries[0])
	}

	// The returned maps must be copies.
	summaries[0].Floors["sqli-error"] = 99
	if state.Floor("alpha.example", "sqli-error") != 3 {
		t.Error("mutating a summary changed the state")
	}
}

func TestFingerprintTableIsWellFormed(t *testing.T) {
	for _, vendor := range vendors {
		if vendor.Name == "" {
			t.Error("a vendor entry has no name")
		}
		if len(vendor.Headers) == 0 && len(vendor.BodyMarkers) == 0 &&
			len(vendor.HeaderValues) == 0 && vendor.ServerContains == "" {
			t.Errorf("vendor %q has no fingerprint at all", vendor.Name)
		}
	}
}

func TestContainsFoldHandlesBothCases(t *testing.T) {
	if !containsFold("Access Denied", "access denied") {
		t.Error("case-insensitive match failed")
	}
	if !containsFold("<body>ACCESS DENIED</body>", "Access Denied") {
		t.Error("case-insensitive match failed on a mixed-case haystack")
	}
	if containsFold("short", "a much longer needle") {
		t.Error("matched a needle longer than the haystack")
	}
	if containsFold("anything", "") {
		t.Error("empty needle matched")
	}
}

func TestBlockedStatusesCoverCommonWAFCodes(t *testing.T) {
	for _, code := range []int{403, 406, 501} {
		if !BlockedStatuses[code] {
			t.Errorf("status %d is not treated as a block code", code)
		}
	}
	if BlockedStatuses[http.StatusOK] {
		t.Error("200 is treated as a block code")
	}
}
